# TODO1.1

number_one = int(input('Введите число, которое вам нравится:'))
number_two = int(input('Введите еще одно число, которое вам нравится:'))
multiplier = '*'
division = '/'
amount = '+'
minus = '-'

def multiplier():
    result_one = number_one * number_two
    print('Ваше выражение {} {} {} = {}'.format(multiplier, number_one, number_two, result_one))
def division():
    result_two = number_one / number_two
    print('Ваше выражение {} {} {} = {}'.format(division, number_one, number_two, result_two))
def amount():
    result_three = number_one + number_two
    print('Ваше выражение {} {} {} = {}'.format(amount, number_one, number_two, result_three))
def subtraction():
    result_four = number_one - number_two
    print('Ваше выражение {} {} {} = {}'.format(minus, number_one, number_two, result_four))

user_input = input('Введите математический символ, с которым хотите взаимодействовать')
if user_input == '*':
      multiplier()
elif user_input == '/':
      division()
elif user_input == '+':
      amount()
elif user_input == '-':
      subtraction()
else:
  print('Введите правильный математический символ. Математика - наука точностей.')

# TODO2.1

num_list = [1, 2, 3, -4, 0]

for number in num_list:
    assert number > 0, 'Warning! В вашем списке есть отрицательное число!'
    # Как продолжить выполнение кода? 

# TODO2.2

try:
  a = int(input('Введите число'))
  b = int(input('Введите число'))
except ValueError:
  print('Введите цело число')
  a/b
except ZeroDivisionError:
  print('На ноль сегодня не делим')
else:
  print('Да, заберите результат: ', a/b)
finally:
  print('С Вами было приятно работать. До новых встреч!')

# TODO3.1

documents = [
 {"number": "x777xx", "name": "Pootin"},
 {"type": "passport", "number": "2207 876234", "name": "Василий Гупкин"},
 {"type": "invoice", "number": "11-2", "name": "Геннадий Покемонов"},
 {"type": "insurance", "number": "10006", "name": "Аристарх Павлов"}
]

directories = {
 '1': ['2207 876234', '11-2'],
 '2': ['10006'],
 '3': []
}

def except_keyerror():
  for persons in documents:
    try:
      print(persons["type"])
    except KeyError:
      print('Тип документа с номером: {} не определен'.format(persons["number"]))
      # break
    finally:
      print('почему этот текст постоянно дублируется, не хочу использовать break :(')

# except_keyerror()
